
services:
  healthapp:
    image: dockerfrancisx/healthapp:v1.0.0
    ports: 
      - "8080:8080"
    environment:
      DB_URL: "jdbc:mysql://mysql:3306/healthapp"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "fr4ncisx"
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: mysql-db
    image: mysql:8.0
    ports: 
      - "3308:3306"
    environment:
      MYSQL_DATABASE: healthapp
      MYSQL_ROOT_PASSWORD: fr4ncisx
    restart: always
